05 20
KarolisTru/angular-shop pull request #3
Opened 2021-05-27 05:26 UTC by KarolisTru

2021-05-27 06:35 UTC, visma-zanas-stundys requested changes

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/app-routing.module.ts
> +  {path: '', component: HomepageComponent},
Try to add prop `pathMatch: 'full'` for routes that have an empty path.

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/core/products.service.ts
> +      .pipe(catchError(this.handleError<any>({})));
Consider if such error handling is useful. Errors are already logged into the console. And `of` in `handleError` silences any errors to be handled. (components will not be able to handle errors)

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components.module.ts
> +    ProductPageComponent,
Consider page components having their own feature modules. Since it's highly unlikely that HomepageComponent will be used multiple times.

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/add-product-modal/add-product-modal.component.html
> +        <button [disabled]="!addProductForm.valid" type="submit">
You can use easier naming of `addProductForm.invalid`

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/add-product-modal/add-product-modal.component.scss
> +  animation-duration: 0.4s;
You can use `animation` shorthand

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/add-product-modal/add-product-modal.component.ts
> +  @Output() onAddProductEvent = new EventEmitter<Product>();
As a convention event emitters should not have a prefix `on`, nor a suffix event. Example: `closeModal`, `addProduct`

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/edit-product-modal/edit-product-modal.component.scss
> +  background-color: rgba(0, 0, 0, 0.4);
Repeating code -- you can make a generic modal component, and put the relevant content into `edit`, `remove`, `add` modals

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/edit-product-modal/edit-product-modal.component.ts
> +  private numberRegEx = /^\s*(?=.*[1-9])\d*(?:\.\d{1,2})?\s*$/;
Consider extracting reused parts of the code to a seperate file, for example `app/utils/validation.ts`

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/edit-product-modal/edit-product-modal.component.ts
> +    });
Consider extracting such form building logic into a product service maybe. Would allow you to reuse code

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/product-card/product-card.component.scss
> +  /*animation: size-up 200ms forwards; -- can't have this one as position fixed for modal doesn't work then*/
Leftover

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/products/products.component.scss
> +    margin-left: calc((100% - 1140px) / 2);
Very weird styles, what is intended here?

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/products/products.component.ts
> +  replaceProductInDOM(updatedProductData: Product) {
No need to mention `InDOM` here

2021-05-27 06:35 UTC, visma-zanas-stundys commented on src/app/shared/components/components/reusable-modal/reusable-modal.component.html
> +  </div>
Did you use this?

2021-05-27 08:40 UTC, KarolisTru commented on src/app/shared/components/components/reusable-modal/reusable-modal.component.html
> +  </div>
Updated, now it's being used.

2021-05-28 11:28 UTC, visma-zanas-stundys requested changes

2021-05-28 11:28 UTC, visma-zanas-stundys commented on src/app/core/product-form.service.ts
> +  generateFormValidation(name = '', photoUrl = '', price = 0, productDescription = '', flagged = false) {
Consider using a single parameter for this method. `generateFormValidation(product?: IProduct)`

2021-05-28 11:28 UTC, visma-zanas-stundys commented on src/app/shared/components/components/reusable-modal/reusable-modal.component.ts
>    }
You can remove this method and use the `modalClose` directly in a template:
```html
<div (click)="modalClose.emit()">
```

2021-05-31 11:55 UTC, merged